#before:
#  hooks:
#    - go mod tidy
dist: release
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
builds:
  - id: luet
    binary: luet
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'github.com/geaaru/luet/pkg/config.BuildTime={{ time "2006-01-02 15:04:05 MST" }}'
      - -X 'github.com/geaaru/luet/pkg/config.BuildCommit={{ .FullCommit }}'
      - -X 'github.com/geaaru/luet/pkg/config.BuildGoVersion={{ .Env.GOVERSION }}'
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7

  - id: luet-build
    dir: luet-build
    binary: luet-build
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'github.com/geaaru/luet/pkg/config.BuildTime={{ time "2006-01-02 15:04:05 MST" }}'
      - -X 'github.com/geaaru/luet/pkg/config.BuildCommit={{ .FullCommit }}'
      - -X 'github.com/geaaru/luet/pkg/config.BuildGoVersion={{ .Env.GOVERSION }}'
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7


archives:
  - id: luet
    builds:
      - luet
    format: binary # this removes the tar of the archives, leaving the binaries alone
    name_template: >-
      luet-{{ .Tag }}-{{ .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{ if .Arm }}v{{ .Arm }}{{ end }}

  - id: luet-build
    builds:
      - luet-build
    format: binary
    name_template: >-
      luet-build-{{ .Tag }}-{{ .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{ if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
release:
  header: |
    Luet is the Macaroni OS Package Manager that uses containers for building packages.
